# Generated by Django 2.1.5 on 2019-07-22 18:34

import Records.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0082_auto_20190624_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailedfield',
            name='_file',
            field=models.FileField(blank=True, null=True, storage=Records.models.CheckDuplicateStorage(), upload_to='C:\\Users\\M McCown\\SCS\\DataMan\\media/files/%Y/', verbose_name='Related file or images'),
        ),
        migrations.AlterField(
            model_name='file',
            name='_file',
            field=models.FileField(storage=Records.models.CheckDuplicateStorage(), upload_to='C:\\Users\\M McCown\\SCS\\DataMan\\media/files/%Y/', verbose_name='File'),
        ),
    ]
