# Generated by Django 2.1.5 on 2019-07-23 19:08

import Records.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0083_auto_20190722_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailedfield',
            name='_file',
        ),
        migrations.AlterField(
            model_name='detailedfield',
            name='_files',
            field=models.ManyToManyField(blank=True, to='Records.File', verbose_name='Related files or images'),
        ),
        migrations.AlterField(
            model_name='file',
            name='_file',
            field=models.FileField(storage=Records.models.CheckDuplicateStorage(), unique=True, upload_to='C:\\Users\\M McCown\\SCS\\DataMan\\media/files/%Y/', verbose_name='File'),
        ),
    ]
